import JSZip from 'jszip';
import { ArchiveItem } from '../types';
import { downloadBlob } from './threeHelpers';

/**
 * Creates and triggers download of a standardized KEEPER Asset Bundle (ZIP)
 * containing:
 *  1. The raw asset file (.glb, .obj, .pdb, .py, .ts, etc.)
 *  2. metadata.json (Structured metadata, metrics, and tags)
 *  3. README.md (Comprehensive usage guide, AI inspection notes, and pipeline specs)
 */
export async function downloadAssetBundle(item: ArchiveItem): Promise<void> {
  const zip = new JSZip();
  const safeBaseName = item.name.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
  const folder = zip.folder(`${safeBaseName}_bundle`) || zip;

  // 1. Asset File
  const assetFileName = `${safeBaseName}.${item.format}`;
  if (item.blob) {
    folder.file(assetFileName, item.blob);
  } else if (item.codeContent) {
    folder.file(assetFileName, item.codeContent);
  } else if (item.sampleType) {
    // Generate sample OBJ text content
    const sampleObjText = `# KEEPER Vault Sample: ${item.name}\n# Format: Wavefront OBJ\no ${safeBaseName}\nv 0.0 0.0 0.0\nv 1.0 0.0 0.0\nv 0.0 1.0 0.0\nf 1 2 3\n`;
    folder.file(assetFileName, sampleObjText);
  } else if (item.pdbId) {
    try {
      const res = await fetch(`https://files.rcsb.org/download/${item.pdbId.toUpperCase()}.pdb`);
      if (res.ok) {
        const pdbText = await res.text();
        folder.file(`${item.pdbId.toUpperCase()}.pdb`, pdbText);
      } else {
        folder.file(assetFileName, `# PDB ID: ${item.pdbId}\nREMARK 250 Access via https://www.rcsb.org/structure/${item.pdbId}\n`);
      }
    } catch {
      folder.file(assetFileName, `# PDB ID: ${item.pdbId}\nREMARK 250 Access via https://www.rcsb.org/structure/${item.pdbId}\n`);
    }
  } else {
    folder.file(assetFileName, `# KEEPER Asset File: ${item.name}\n`);
  }

  // 2. Metadata JSON
  const metadataPayload = {
    vault_version: '2.0-keeper',
    id: item.id,
    name: item.name,
    description: item.description,
    category: item.category,
    format: item.format,
    size_bytes: item.size,
    tier: item.tier,
    tags: item.tags,
    dateAdded: item.dateAdded,
    author: item.author || 'KEEPER Vault Contributor',
    license: item.license || 'Proprietary / Vault Use',
    version: item.version || '1.0.0',
    compatibility: item.compatibility || ['Blender 4.2', 'Three.js r160'],
    aiAnalysis: item.aiAnalysis || null,
    stats: item.stats || null,
  };
  folder.file('metadata.json', JSON.stringify(metadataPayload, null, 2));

  // 3. Usage README.md
  const readmeContent = `# ${item.name}
**KEEPER Vault Asset Bundle** | **Tier:** ${item.tier.toUpperCase()} | **Format:** .${item.format.toUpperCase()}

---

## 1. Overview & Description
${item.description}

* **Author:** ${item.author || 'KEEPER Vault'}
* **Version:** ${item.version || '1.0.0'}
* **License:** ${item.license || 'Vault Community Standard'}
* **Added:** ${new Date(item.dateAdded).toLocaleDateString()}
* **Tags:** ${item.tags.map((t) => '`' + t + '`').join(', ')}

---

## 2. Pipeline & Engine Compatibility
${
  item.compatibility && item.compatibility.length > 0
    ? item.compatibility.map((c) => `- **Verified:** ${c}`).join('\n')
    : '- **Verified:** Blender 4.2 LTS, Three.js r160, WebGL 2.0'
}

---

## 3. Integration & Usage Guide

${
  item.category === 'script' || item.category === 'shader'
    ? `### Execution Instructions
\`\`\`bash
# Run in compatible runtime environment
${item.format === 'py' ? `python3 ${assetFileName}` : `npm run build / compile`}
\`\`\`
${item.aiAnalysis?.documentation || ''}`
    : item.category === 'molecular'
    ? `### Molecular Visualization
- Open with **Mol* Viewer**, **PyMOL 3.0**, or **UCSF ChimeraX**.
- Load coordinate file \`${assetFileName}\` directly.
- Suggested color scheme: Secondary Structure / Chain ID.`
    : `### 3D Engine Setup
- **Blender 4.2:** File > Import > ${item.format.toUpperCase()}
- **Three.js WebGL:**
\`\`\`javascript
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
const loader = new GLTFLoader();
loader.load('${assetFileName}', (gltf) => {
  scene.add(gltf.scene);
});
\`\`\``
}

---

## 4. AI Deep Technical Inspection Report
*Analyzed via Gemini 3.8 Flash (KEEPER Inspection Engine)*

${
  item.aiAnalysis
    ? `### Executive Summary
${item.aiAnalysis.summary}

### Mesh Topology / Code Quality Critique
${item.aiAnalysis.topologyOrQuality}

### Recommended Performance & Production Tips
${item.aiAnalysis.performanceTips.map((tip) => `- ${tip}`).join('\n')}

### Verified Pipeline Compatibility Notes
${item.aiAnalysis.compatibilityNotes || 'Certified for production pipelines.'}
`
    : `*Run an AI Deep Analysis inside KEEPER Vault to attach detailed topological and algorithmic reports to this bundle.*`
}

---
*Generated by El-Roi / KEEPER 3D & Script Vault.*
`;

  folder.file('README.md', readmeContent);

  // Generate zip Blob and download
  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, `${safeBaseName}_bundle.zip`);
}
